# For example:
multiprocessing: False
path_pretrained_models: './pretrained_models'
dataset:
    data_path: 'data'
blip_v2_model_type: blip2-flan-t5-xxl  # Change to blip2-flan-t5-xl for smaller GPUs
blip_half_precision: True
# Add more changes here, following the same format as base_config.yaml
gpt3:
    model: gpt-4o-mini                       # gpt-4o, deepseek
    max_tokens: 512
codex:
    model: gpt-4o-mini                       # gpt-4o, gpt-4o-mini, deepseek
    max_tokens: 10000
    prompt: ./prompts/pkgvqa_gpt.prompt
fixed_code_file: ./prompts/fixed_code/blip2_video.prompt
select_answer_prompt: ./prompts/select_answer.prompt
